spring.application.name=ApiGateway-4SA11
server.port=8093

# Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ========================
# ROUTES CONFIGURATION
# ========================

# DEMANDS
spring.cloud.gateway.routes[0].id=demand
spring.cloud.gateway.routes[0].uri=http://localhost:8089
spring.cloud.gateway.routes[0].predicates[0]=Path=/demands/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/demands/(?<segment>.*), /internshipDemands/api/demands/${segment}

# EVALUATIONS
spring.cloud.gateway.routes[1].id=evaluation
spring.cloud.gateway.routes[1].uri=http://localhost:8089
spring.cloud.gateway.routes[1].predicates[0]=Path=/evaluations/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/evaluations/(?<segment>.*), /internshipDemands/api/evaluations/${segment}

# NOTIFICATIONS
spring.cloud.gateway.routes[2].id=notification
spring.cloud.gateway.routes[2].uri=http://localhost:8089
spring.cloud.gateway.routes[2].predicates[0]=Path=/notifications/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/notifications/(?<segment>.*), /internshipDemands/api/notifications/${segment}

# RESPONSES
spring.cloud.gateway.routes[3].id=response
spring.cloud.gateway.routes[3].uri=http://localhost:8089
spring.cloud.gateway.routes[3].predicates[0]=Path=/responses/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/responses/(?<segment>.*), /internshipDemands/api/responses/${segment}

# ========================
# DEBUG LOGGING
# ========================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
